---
- name: Deploy CrowdStrike Falcon Sensor
  hosts: falcon_hosts
  vars:
    falcon_tags: "GCP/us-central1,Lab,ansible-deployed"

  roles:
    - role: crowdstrike.falcon.falcon_install
      vars:
        falcon_sensor_version_decrement: 2

    - role: crowdstrike.falcon.falcon_configure
      vars:
        falcon_tags: "{{ falcon_tags }}"
