[debian12]
falcon-linux-deb-12 ansible_host=<YOUR_HOST_IP_1>

[debian13]
falcon-linux-deb-13 ansible_host=<YOUR_HOST_IP_2>

[falcon_hosts:children]
debian12
debian13

[falcon_hosts:vars]
ansible_user=<YOUR_SSH_USER>
ansible_ssh_private_key_file=~/.ssh/google_compute_engine
ansible_ssh_common_args=-o StrictHostKeyChecking=no
